/* This is a generated file. Do not edit. */
#include "icon-names.h"

static const char *action_icon_name[] =
{
  "analyze-bivariate-correlation", 
  "analyze-compare-means", 
  "analyze-descriptive-statistics", 
  "analyze-factor-analysis", 
  "analyze-kmeans-cluster", 
  "analyze-non-parametric-statistics", 
  "analyze-realiability", 
  "analyze-regression", 
  "analyze-roc-curve", 
  "analyze-univariate-analysis", 
  "data-aggregate", 
  "data-select-cases", 
  "data-sort-cases", 
  "data-split-file", 
  "data-transpose", 
  "data-weight-cases", 
  "display-information-external-file", 
  "display-information-working-file", 
  "edit-clear", 
  "edit-copy", 
  "edit-cut", 
  "edit-delete", 
  "edit-find", 
  "edit-go-to-case", 
  "edit-go-to-variable", 
  "edit-insert-case", 
  "edit-insert-variable", 
  "edit-paste", 
  "edit-redo", 
  "edit-select-all", 
  "edit-undo", 
  "file-display-information", 
  "file-export-data", 
  "file-import-data", 
  "file-new-data", 
  "file-open-data", 
  "file-print", 
  "file-quit", 
  "file-recently-used", 
  "file-rename-data-set", 
  "file-save-as", 
  "file-save-data", 
  "file-syntax-data", 
  "file-system-data", 
  "help-about", 
  "help-reference-manual", 
  "run-all", 
  "run-current-line", 
  "run-selection", 
  "run-to-end", 
  "transform-automatic-recode", 
  "transform-compute", 
  "transform-count", 
  "transform-in-to-different-variables", 
  "transform-in-to-same-variables", 
  "transform-rank-cases", 
  "transform-run-pending", 
  "utilities-data-file-comments", 
  "utilities-variables", 
  "view-font", 
  "view-value-labels", 
  "windows-minimize-all", 
  "windows-split", 
};

const struct icon_context action_icon_context = {
  action_icon_name,
  sizeof (action_icon_name) / sizeof (action_icon_name[0]),
  "actions"
};

static const char *category_icon_name[] =
{
  "align-center", 
  "align-left", 
  "align-right", 
  "measure-currency-nominal", 
  "measure-currency-ordinal", 
  "measure-currency-scale", 
  "measure-date-nominal", 
  "measure-date-ordinal", 
  "measure-date-scale", 
  "measure-nominal", 
  "measure-ordinal", 
  "measure-scale", 
  "measure-string-nominal", 
  "measure-string-ordinal", 
  "measure-time-nominal", 
  "measure-time-ordinal", 
  "measure-time-scale", 
  "role-both", 
  "role-input", 
  "role-none", 
  "role-partition", 
  "role-split", 
  "role-target", 
};

const struct icon_context category_icon_context = {
  category_icon_name,
  sizeof (category_icon_name) / sizeof (category_icon_name[0]),
  "categories"
};

